# get base image
FROM node:18.2.0-alpine3.14

# set working directory in container
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# copy package.json to work directory
COPY package.json ./
COPY package-lock.json ./

# install app dependencies
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install --silent

# Copy the src files to work directory
COPY . ./

# This is only for readability reasons. 
# The port should be exposed when running `docker run`
EXPOSE 3000

# start app
CMD ["npm", "start"]